; ============================================
;  NexHome - ESP8266 Node Chính
;  Board: NodeMCU v2 (ESP8266)
;  Chức năng: DHT11 + Relay + PIR + Nút bấm
; ============================================

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    tzapu/WiFiManager @ ^0.16.0

; Fix lỗi kẹt tín hiệu DTR/RTS khi mở Serial Monitor
monitor_rts = 0
monitor_dtr = 0