; ============================================
;  NexHome - ESP32-CAM Node
;  Board: AI Thinker ESP32-CAM
;  Chức năng: Camera MJPEG Stream + Flash LED
; ============================================

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    https://github.com/tzapu/WiFiManager.git

; Fix lỗi kẹt tín hiệu DTR/RTS khi mở Serial Monitor
monitor_rts = 0
monitor_dtr = 0
